import pygame as p
import constants as c
from engine import GameState
from controller import InputHandler
from renderer import Renderer

def main() -> None:
    """
    Main driver running the game loop. Coordinates Model, View, and Controller.
    Handles the transition between Main Menu, Color Selection, and Game state.
    """
    p.init()
    screen = p.display.set_mode((c.WIDTH, c.HEIGHT))
    p.display.set_caption("Chess Project - MVC Architecture")
    clock = p.time.Clock()
    
    gs = GameState()            
    input_handler = InputHandler() 
    renderer = Renderer()       
    
    running = True
    
    # State machine variable to control which screen is currently active and rendered
    app_state = 'main_menu'
    
    # Flags defining if a human is playing a specific color. Used to block inputs for AI turns.
    player_one = True # Controls White
    player_two = True # Controls Black
    
    # Variables to store button collision rectangles generated by the renderer
    pvp_btn, pve_btn, quit_btn = None, None, None
    white_btn, black_btn, back_btn = None, None, None

    while running:
        for event in p.event.get():
            if event.type == p.QUIT:
                running = False
                
            elif event.type == p.MOUSEBUTTONDOWN:
                location = p.mouse.get_pos()
                
                # Route the mouse click event based on the current screen state
                if app_state == 'main_menu':
                    # Set up a local game where human controls both sides
                    if pvp_btn and pvp_btn.collidepoint(location):
                        player_one = True
                        player_two = True
                        app_state = 'game'
                    # Move to the sub-menu to choose color for AI match
                    elif pve_btn and pve_btn.collidepoint(location):
                        app_state = 'color_menu'
                    # Exit the application entirely
                    elif quit_btn and quit_btn.collidepoint(location):
                        running = False

                elif app_state == 'color_menu':
                    # Start game: Human is White, AI is Black
                    if white_btn and white_btn.collidepoint(location):
                        player_one = True
                        player_two = False
                        app_state = 'game'
                    # Start game: AI is White, Human is Black
                    elif black_btn and black_btn.collidepoint(location):
                        player_one = False
                        player_two = True
                        app_state = 'game'
                        is_board_flipped = not player_one and player_two
                    # Cancel AI match setup and return to the primary screen
                    elif back_btn and back_btn.collidepoint(location):
                        app_state = 'main_menu'

                elif app_state == 'game':
                    # Only process board clicks if it is a human player's turn
                    human_turn = (gs.white_to_move and player_one) or (not gs.white_to_move and player_two)
                    if human_turn:
                        input_handler.handle_mouse_click(location, gs, is_board_flipped)
                
            elif event.type == p.KEYDOWN:
                # Allow undo action only when actively playing the game
                if event.key == p.K_z and app_state == 'game':  
                    gs.undo_move()
                    input_handler.reset_clicks()
                    
                # The Escape key acts as a 'resign/abort' button, resetting the state and returning to menu
                elif event.key == p.K_ESCAPE and app_state == 'game':
                    app_state = 'main_menu'
                    gs = GameState()
                    input_handler.reset_clicks()

        # Render the graphics corresponding to the current state machine value
        if app_state == 'main_menu':
            pvp_btn, pve_btn, quit_btn = renderer.draw_main_menu(screen)
        elif app_state == 'color_menu':
            white_btn, black_btn, back_btn = renderer.draw_color_menu(screen)
        elif app_state == 'game':
            renderer.draw_game_state(screen, gs, input_handler.sq_selected, input_handler.valid_moves, is_board_flipped)
            # Display the pawn promotion UI overlay if a pawn reached the final rank
            if input_handler.is_promoting:
                start_row, start_col = input_handler.promotion_move[0]
                piece_color = gs.board[start_row][start_col].color
                renderer.draw_promotion_menu(screen, piece_color)

        p.display.flip()
        clock.tick(c.MAX_FPS)

if __name__ == "__main__":
    main()